# Generated by Django 5.2.8 on 2025-11-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('min_gpax', models.FloatField(default=0.0)),
                ('min_gpamath', models.FloatField(blank=True, null=True)),
                ('min_gpasci', models.FloatField(blank=True, null=True)),
                ('min_gpalan', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
